import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { NextConfig } from "next";
import { initOpenNextCloudflareForDev } from "@opennextjs/cloudflare";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Slugs imported from the legacy WordPress site, redirected /<slug> → /writing/<slug>.
// Generated by scripts/import-wp.mjs into drizzle/imports/wp-redirects.json.
// Filter out paths that collide with first-class App Router routes.
const RESERVED_TOP_LEVEL = new Set([
  "writing",
  "projects",
  "now",
  "about",
  "admin",
  "api",
  "_next",
]);

const wpSlugs: string[] = JSON.parse(
  readFileSync(join(__dirname, "drizzle/imports/wp-redirects.json"), "utf8"),
);
const wpRedirects = wpSlugs
  .filter((slug) => !RESERVED_TOP_LEVEL.has(slug))
  .map((slug) => ({
    source: `/${slug}`,
    destination: `/writing/${slug}`,
    permanent: true,
  }));

const nextConfig: NextConfig = {
  reactStrictMode: true,
  experimental: {
    reactCompiler: false,
  },
  async redirects() {
    return wpRedirects;
  },
};

initOpenNextCloudflareForDev();

export default nextConfig;
