-- Auto-generated by scripts/generate-seed.mjs — do not edit by hand.
-- Apply via:  pnpm db:seed:local   (or  pnpm db:seed:remote  for production).
-- This file only seeds the tag taxonomy. Post/project content is imported
-- separately (see scripts/import-wp.mjs).

DELETE FROM comments;
DELETE FROM posts;
DELETE FROM tags;
DELETE FROM projects;
DELETE FROM subscribers;
DELETE FROM settings;

INSERT INTO tags (id, label, hint, color, sort) VALUES ('cpp', 'C++', '现代 C++ 实践与底层', 'cpp', 1);
INSERT INTO tags (id, label, hint, color, sort) VALUES ('win', 'Windows', 'Win32 / WinRT / 调试', 'win', 2);
INSERT INTO tags (id, label, hint, color, sort) VALUES ('ai', 'AI', 'LLM 工具链与思考', 'ai', 3);
INSERT INTO tags (id, label, hint, color, sort) VALUES ('note', '随笔', '关于工程师生活', 'note', 4);
INSERT INTO tags (id, label, hint, color, sort) VALUES ('tool', '工具', '开发环境与小品', 'tool', 5);
