/**
 * Generates drizzle/seed.sql — only the fixed tag taxonomy.
 * Posts and projects are imported separately via scripts/import-wp.mjs.
 * Run via `pnpm gen:seed` (alias for `node scripts/generate-seed.mjs`).
 *
 * Keep SEED_TAGS aligned with `src/lib/seed-data.ts`.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

const SEED_TAGS = [
  { id: "cpp", label: "C++", hint: "现代 C++ 实践与底层", color: "cpp", sort: 1 },
  { id: "win", label: "Windows", hint: "Win32 / WinRT / 调试", color: "win", sort: 2 },
  { id: "ai", label: "AI", hint: "LLM 工具链与思考", color: "ai", sort: 3 },
  { id: "note", label: "随笔", hint: "关于工程师生活", color: "note", sort: 4 },
  { id: "tool", label: "工具", hint: "开发环境与小品", color: "tool", sort: 5 },
];

const sql = (s) => `'${String(s).replace(/'/g, "''")}'`;

let out = `-- Auto-generated by scripts/generate-seed.mjs — do not edit by hand.
-- Apply via:  pnpm db:seed:local   (or  pnpm db:seed:remote  for production).
-- This file only seeds the tag taxonomy. Post/project content is imported
-- separately (see scripts/import-wp.mjs).

DELETE FROM comments;
DELETE FROM posts;
DELETE FROM tags;
DELETE FROM projects;
DELETE FROM subscribers;
DELETE FROM settings;

`;

for (const t of SEED_TAGS) {
  out += `INSERT INTO tags (id, label, hint, color, sort) VALUES (${sql(t.id)}, ${sql(t.label)}, ${sql(t.hint)}, ${sql(t.color)}, ${t.sort});\n`;
}

const outPath = join(repoRoot, "drizzle", "seed.sql");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out, "utf8");
console.log(`Wrote ${outPath} (${out.length} bytes, ${SEED_TAGS.length} tags).`);
